// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEQkDTSjNikxsxjMLKCYdJ4BSOTEoCO_4',
    appId: '1:830594518730:web:b1e384f2e830b4323e2e33',
    messagingSenderId: '830594518730',
    projectId: 'gym-tracker-9925c',
    authDomain: 'gym-tracker-9925c.firebaseapp.com',
    storageBucket: 'gym-tracker-9925c.firebasestorage.app',
    measurementId: 'G-9685YJL1YD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOEfzqyqAsCCIpxowhi0bJJcsAmp1_oCA',
    appId: '1:830594518730:android:83575990bf418cbd3e2e33',
    messagingSenderId: '830594518730',
    projectId: 'gym-tracker-9925c',
    storageBucket: 'gym-tracker-9925c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD51ebLXqL4DK79x7c9xUoxYa3LWmjGV10',
    appId: '1:830594518730:ios:11adc1d95be376203e2e33',
    messagingSenderId: '830594518730',
    projectId: 'gym-tracker-9925c',
    storageBucket: 'gym-tracker-9925c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD51ebLXqL4DK79x7c9xUoxYa3LWmjGV10',
    appId: '1:830594518730:ios:11adc1d95be376203e2e33',
    messagingSenderId: '830594518730',
    projectId: 'gym-tracker-9925c',
    storageBucket: 'gym-tracker-9925c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEQkDTSjNikxsxjMLKCYdJ4BSOTEoCO_4',
    appId: '1:830594518730:web:ef72dfe538085da73e2e33',
    messagingSenderId: '830594518730',
    projectId: 'gym-tracker-9925c',
    authDomain: 'gym-tracker-9925c.firebaseapp.com',
    storageBucket: 'gym-tracker-9925c.firebasestorage.app',
    measurementId: 'G-H4EKYTCNDE',
  );
}
