// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHHsWjLW_2yEq8zeD_9gB1ssUa8cuMwFM',
    appId: '1:942600708331:web:8fc9bc6207c454ee95deae',
    messagingSenderId: '942600708331',
    projectId: 'nutribalance-app-11a09',
    authDomain: 'nutribalance-app-11a09.firebaseapp.com',
    storageBucket: 'nutribalance-app-11a09.firebasestorage.app',
    measurementId: 'G-P6F2BW6QTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_D0ULHVcDoNwbUD7DQW3gV66oXS-wo0I',
    appId: '1:942600708331:android:ba4a1ccb69a4024495deae',
    messagingSenderId: '942600708331',
    projectId: 'nutribalance-app-11a09',
    storageBucket: 'nutribalance-app-11a09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHzM0Bd6mkUMoksSfZFddxb1mbrsE86dg',
    appId: '1:942600708331:ios:557d359f99353f3595deae',
    messagingSenderId: '942600708331',
    projectId: 'nutribalance-app-11a09',
    storageBucket: 'nutribalance-app-11a09.firebasestorage.app',
    iosClientId: '942600708331-tepi705bcitaqr956p3k1kjp4pj22poa.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHzM0Bd6mkUMoksSfZFddxb1mbrsE86dg',
    appId: '1:942600708331:ios:557d359f99353f3595deae',
    messagingSenderId: '942600708331',
    projectId: 'nutribalance-app-11a09',
    storageBucket: 'nutribalance-app-11a09.firebasestorage.app',
    iosClientId: '942600708331-tepi705bcitaqr956p3k1kjp4pj22poa.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHHsWjLW_2yEq8zeD_9gB1ssUa8cuMwFM',
    appId: '1:942600708331:web:829136da0e71bb6f95deae',
    messagingSenderId: '942600708331',
    projectId: 'nutribalance-app-11a09',
    authDomain: 'nutribalance-app-11a09.firebaseapp.com',
    storageBucket: 'nutribalance-app-11a09.firebasestorage.app',
    measurementId: 'G-Z0KXLWVV0Z',
  );

}